In [1]:
import numpy as np 

# Comparison Matrix of nxn
def comp_matrix(w):
    #w=np.array([0.9218, 0.7382, 0.1763 ,0.4057])
    a=sorted(w)
    a=np.array(a)
    # print(len(w))
    n=len(w)
    b=np.array([0 for i in range(n)])
    #w=np.append(w,[6])
    #print(w,a)
    for i in range(n):
        for j in range(n):
            if(a[i]==w[j]):
                b[i]=j
    for i in range(n):
        b[i]=int(b[i])
    print(b)

    # initial creation of comparison matrix
    c=np.zeros([m,m])
    #print(c,"\n")
    for j in range(m):
        c[b[0]][j]=1
    #print(c,"\n")
    for i in range(1,m):
        if(a[i]==a[i-1]):
            for j in range(m):
                c[b[i]][j]=c[b[i-1]][j]
        else:
            for j in range(i,m):
                c[b[i]][b[j]]=1
    #print(c)
    return c

# Dominance Degree Matrix
def dom_matrix(p,n,m):
    d=np.zeros([m,m])
    #let: m=3
    # Dom matrix d by summation of consecutive comparison matrix per objective of the solution
    for j in range(n):
        w=p[j]
        #print(w)
        c=comp_matrix(w)
        d=d+c
    print(d)
    for i in range(m):
        for j in range(i,m):
            if(d[i][j]==n and d[j][i]==n):
                d[i][j], d[j][i]=0,0
    print(d)
    return d

# ENS-DDA
def ens_dda(n,m):
    p=np.random.rand(n,m)
    print(p)
    d=dom_matrix(p,n,m)
    print(p)
    # sort p based on the 1st obj
    for i in range(m):
        for j in range(i,m):
            if(p[:,i][0]>p[:,j][0]):
                p[:,[i,j]]=p[:,[j,i]]
    print(p)
    c=0 #loop counter
    #insertion of fronts for all solutions
    for s in range(m):
        fr_insert(p[:,s],f,nf,d,n,m,c)
        c=c+1
    print(f)

def fr_insert(s,f,nf,d,n,m,c):
    isIn=False
    for k in range(nf+1):
        isDom=False
        #check if soln objs dominant
        for sd in f[k]:
            for sdd in range(m):
                if(d[sdd][c]==n):
                    isDom=True
                    break
        #if not then insert to the fronts
        if(isDom==False):
            f[k].append([s])
            isIn=True
            break
    if(isIn==False):
        print("Hello")
        nf=nf+1
        f.append([])
        f[nf].append([s]) 

# main
nf=0
n=4
m=3
f=[[]]
ens_dda(n,m)

[[0.29063041 0.76638195 0.23128572]
 [0.78989136 0.17599774 0.99885867]
 [0.05068734 0.23324089 0.23577075]
 [0.40704611 0.6039093  0.83621634]]
[2 0 1]
[1 0 2]
[0 1 2]
[0 1 2]
[[4. 3. 3.]
 [1. 4. 3.]
 [1. 1. 4.]]
[[0. 3. 3.]
 [1. 0. 3.]
 [1. 1. 0.]]
[[0.29063041 0.76638195 0.23128572]
 [0.78989136 0.17599774 0.99885867]
 [0.05068734 0.23324089 0.23577075]
 [0.40704611 0.6039093  0.83621634]]
[[0.23128572 0.29063041 0.76638195]
 [0.99885867 0.78989136 0.17599774]
 [0.23577075 0.05068734 0.23324089]
 [0.83621634 0.40704611 0.6039093 ]]
[[[array([0.23128572, 0.99885867, 0.23577075, 0.83621634])], [array([0.29063041, 0.78989136, 0.05068734, 0.40704611])], [array([0.76638195, 0.17599774, 0.23324089, 0.6039093 ])]]]
